# deepai key 设置
#使用deepai需要 npm install --save deepai  or  cnpm install deepai
#否则会报错 [ERROR] error - Error: Cannot find module 'deepai' 
deepai: 
  # get your free API key at https://deepai.org
  # 从上面网址获取免费的API key 注意需要邮箱注册并验证
  key: 

# 腾讯图像分析 key 设置  不设置则不使用腾讯增强
#[ERRO] Error: Cannot find module 'tencentcloud-sdk-nodejs'
#cnpm install tencentcloud-sdk-nodejs
tencent: 
  SecretId: 
  SecretKey: 