# import command from '../command/command.js'
# await command.getConfig("", "");
# 青云客 设置
qykai_cfg: 
  # 是否全局点赞
  everyone: true 
  # 是否有点赞提示
  reply: true

# 点赞 设置
thumbUp_cfg: 
  gailv: 0.1
  gailv_: 0.1

# 决斗 设置
duel_cfg: 
  # 天时地利依赖系数，这个越大，战斗的随机性越大
  Magnification: 1
  # 命令间隔时间，单位秒，这是决斗的冷却时间#初始为300秒
  Cooling_time: 300
  # 命令间隔时间，单位分钟，这是修炼的冷却时间#初始为300分钟
  Cooling_time2: 300
  # 命令间隔时间，单位分钟，这是突破的冷却时间#初始为30分钟
  Cooling_time3: 30