# import command from '../command/command.js'
# await command.getConfig("", "");
# 插件出现问题就重新拉取，就是重装的意思
# 点赞 设置
thumbUp_cfg: 
  # 是否全局点赞(还需要你点赞名单为空)和是否回复提醒,1是，2否
  everyone: 1 
  reply_something: 2
  # 最短点赞时间间隔，单位毫秒
  time: 60000

# 青云客 设置:初始概率和，每次改变量
qykai_cfg: 
  gailv: 0.5
  gailv_: 0.1

# 决斗系列插件 设置
duel_cfg: 
  # 天时地利依赖系数，这个越大，战斗的随机性越大
  Magnification: 1
  # 命令间隔时间，单位秒，这是决斗的冷却时间#初始为300秒
  Cooling_time: 300
  # 命令间隔时间，单位分钟，这是修炼的冷却时间#初始为300分钟
  Cooling_time2: 300
  # 命令间隔时间，单位分钟，这是突破的冷却时间#初始为30分钟
  Cooling_time3: 30